/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sms;

import com.sms.entity.Kontak;
import com.sms.entity.Group;
import com.sms.utils.Format;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Vector;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SmsGUI extends javax.swing.JFrame {

    SmsService sms = null;
    ScheduledExecutorService exec = null;

    Group selectedGroup = null;
    Kontak selectedContact = null;

    /**
     * Creates new form SmsGUI
     */
    public SmsGUI() {

        initComponents();

        sms = new SmsService();
        exec = Executors.newSingleThreadScheduledExecutor();
        exec.scheduleAtFixedRate(() -> {
            lblStatus.setText(String.valueOf(sms.getStatus()));
        }, 0, 1, TimeUnit.SECONDS);

        InputMap im = tblKontak.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap am = tblKontak.getActionMap();

        KeyStroke enterKey = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);

        im.put(enterKey, "Action.enter");
        am.put("Action.enter", new AbstractAction() {
            public void actionPerformed(ActionEvent evt) {

                tblKontak.changeSelection(tblKontak.getSelectedRow(), 1, false, false);
                if (!tblKontak.editCellAt(tblKontak.getSelectedRow(), 1)) {
                    JOptionPane.showMessageDialog(tblKontak, "Failed to start cell editing");
                }
            }
        });
        displayContacts(sms.getDB().getKontaks());
        displayGroups(sms.getDB().getGroups());
    }

    private void refreshAll() {
        displayGroups(sms.getDB().getGroups());
        displayContacts(sms.getDB().getKontaks());
    }

    public void displayContacts(List list) {

        Vector<String> tableHeaders = new Vector<>();
        Vector tableData = new Vector();

        tableHeaders.add("No");
        tableHeaders.add("Nama");
        tableHeaders.add("Nomor");

        for (Object obj : list) {

            Kontak mobiles = (Kontak) obj;
            Vector<Object> row = new Vector<>();

            row.add(mobiles.getKontakId());
            row.add(mobiles.getContactName());
            row.add(mobiles.getContactPhone());

            tableData.add(row);
        }
        tblKontak.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    public void displayGroups(List list) {
        DefaultTableModel dtm = new DefaultTableModel();
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        cbm.removeAllElements();
        dtm.setRowCount(0);

        dtm.addColumn("No");
        dtm.addColumn("Kode");
        dtm.addColumn("Nama");
        cbm.addElement("Pilih grup");

        for (Object obj : list) {

            Group grup = (Group) obj;

            cbm.addElement(grup);

            Vector<Object> row = new Vector<>();

            row.add(grup.getGroupId());
            row.add(grup.getGroupCode());
            row.add(grup.getGroupName());
            dtm.addRow(row);

        }
        cbGrup.setModel(cbm);
        tblGrup.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSendSMS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesan = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        pnlInbox = new javax.swing.JPanel();
        pnlContacts = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKontak = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblNomor = new javax.swing.JLabel();
        txtKontakNomor = new javax.swing.JTextField();
        txtKontakNama = new javax.swing.JTextField();
        btnAddKontak = new javax.swing.JButton();
        btnUpdateKontak = new javax.swing.JButton();
        btnDeleteKontak = new javax.swing.JButton();
        lblNomor1 = new javax.swing.JLabel();
        cbGrup = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGrup = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtGrupNama = new javax.swing.JTextField();
        lblNomor2 = new javax.swing.JLabel();
        txtGrupKode = new javax.swing.JTextField();
        btnAddGrup = new javax.swing.JButton();
        btnUpdateGrup = new javax.swing.JButton();
        btnDeleteGrup = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS Center");
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setText("Phone number : ");

        jLabel2.setText("Message :");

        txtPesan.setColumns(20);
        txtPesan.setRows(5);
        jScrollPane1.setViewportView(txtPesan);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSendSMSLayout = new javax.swing.GroupLayout(pnlSendSMS);
        pnlSendSMS.setLayout(pnlSendSMSLayout);
        pnlSendSMSLayout.setHorizontalGroup(
            pnlSendSMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSendSMSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSendSMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        pnlSendSMSLayout.setVerticalGroup(
            pnlSendSMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSendSMSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSend)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Send SMS", pnlSendSMS);

        javax.swing.GroupLayout pnlInboxLayout = new javax.swing.GroupLayout(pnlInbox);
        pnlInbox.setLayout(pnlInboxLayout);
        pnlInboxLayout.setHorizontalGroup(
            pnlInboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        pnlInboxLayout.setVerticalGroup(
            pnlInboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inbox", pnlInbox);

        tblKontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Nomor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblKontak);
        if (tblKontak.getColumnModel().getColumnCount() > 0) {
            tblKontak.getColumnModel().getColumn(0).setMinWidth(50);
        }

        jLabel3.setText("Nama :");

        lblNomor.setText("Nomor :");

        btnAddKontak.setText("Add");
        btnAddKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKontakActionPerformed(evt);
            }
        });

        btnUpdateKontak.setText("Update");

        btnDeleteKontak.setText("Delete");

        lblNomor1.setText("Grup :");

        javax.swing.GroupLayout pnlContactsLayout = new javax.swing.GroupLayout(pnlContacts);
        pnlContacts.setLayout(pnlContactsLayout);
        pnlContactsLayout.setHorizontalGroup(
            pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContactsLayout.createSequentialGroup()
                        .addComponent(btnAddKontak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateKontak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteKontak))
                    .addGroup(pnlContactsLayout.createSequentialGroup()
                        .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomor)
                            .addComponent(jLabel3)
                            .addComponent(lblNomor1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKontakNama, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtKontakNomor, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(cbGrup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        pnlContactsLayout.setVerticalGroup(
            pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKontakNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomor)
                    .addComponent(txtKontakNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomor1)
                    .addComponent(cbGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddKontak)
                    .addComponent(btnUpdateKontak)
                    .addComponent(btnDeleteKontak))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contacts", pnlContacts);

        tblGrup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblGrup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblGrupMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblGrup);
        if (tblGrup.getColumnModel().getColumnCount() > 0) {
            tblGrup.getColumnModel().getColumn(0).setMinWidth(50);
        }

        jLabel4.setText("Nama :");

        lblNomor2.setText("Kode :");

        btnAddGrup.setText("Add");
        btnAddGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrupActionPerformed(evt);
            }
        });

        btnUpdateGrup.setText("Update");
        btnUpdateGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGrupActionPerformed(evt);
            }
        });

        btnDeleteGrup.setText("Delete");
        btnDeleteGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGrupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomor2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGrupNama)
                            .addComponent(txtGrupKode, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddGrup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateGrup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteGrup)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGrupNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomor2)
                    .addComponent(txtGrupKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGrup)
                    .addComponent(btnUpdateGrup)
                    .addComponent(btnDeleteGrup))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Groups", jPanel1);

        btnStart.setText("Start");
        btnStart.setName("btnStart"); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.setToolTipText("");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(551, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStart)
                        .addComponent(btnStop)))
                .addContainerGap())
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addComponent(jTabbedPane1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlMain, "card2");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Logs");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        sms.startService();
        btnStart.setEnabled(false);
        btnStop.setEnabled(true);

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        sms.stopService();
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String phone = txtNomor.getText();
        String msg = txtPesan.getText();
        int cond = sms.sendMessage(phone, msg);
        switch (cond) {
            case 1:
                JOptionPane.showMessageDialog(null, "Format Nomor salah");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Service is not STARTED");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Pesan Terkirim");
                break;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnUpdateGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGrupActionPerformed

        if (this.selectedGroup != null) {
            if (!txtGrupNama.getText().isEmpty() && !txtGrupKode.getText().isEmpty()) {
                this.selectedGroup.setGroupName(txtGrupNama.getText());
                this.selectedGroup.setGroupCode(txtGrupKode.getText());
                sms.getDB().updateGroup(selectedGroup);
                refreshAll();
            } else {
                JOptionPane.showMessageDialog(null, "Group name atau code tidak boleh kosong");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateGrupActionPerformed

    private void tblGrupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGrupMousePressed
        int row = tblGrup.getSelectedRow();
        int id = Integer.valueOf(tblGrup.getValueAt(row, 0).toString());
        this.selectedGroup = sms.getDB().getGroup(id);
        if (this.selectedGroup != null) {
            String nama = this.selectedGroup.getGroupName();
            String kode = this.selectedGroup.getGroupCode();
            txtGrupNama.setText(nama);
            txtGrupKode.setText(kode);
        }
    }//GEN-LAST:event_tblGrupMousePressed

    private void btnAddGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrupActionPerformed
        if (!txtGrupNama.getText().isEmpty() && !txtGrupKode.getText().isEmpty()) {
            Group g = new Group();
            g.setGroupName(txtGrupNama.getText());
            g.setGroupCode(txtGrupKode.getText());
            sms.getDB().insertGroup(g);
            refreshAll();
        } else {
            JOptionPane.showMessageDialog(null, "Group name atau code tidak boleh kosong");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGrupActionPerformed

    private void btnDeleteGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGrupActionPerformed
        if (this.selectedGroup != null) {
            int opt = JOptionPane.showConfirmDialog(null, "Hapus data grup ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            switch (opt) {
                case JOptionPane.YES_OPTION:
                    sms.getDB().deleteGroup(selectedGroup);
                    refreshAll();
                    break;
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGrupActionPerformed

    private void btnAddKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKontakActionPerformed
        if (!txtKontakNama.getText().isEmpty() && !txtKontakNomor.getText().isEmpty()) {
            String phone = txtKontakNomor.getText();
            if (Format.cekPhoneFormat(phone)) {
                Kontak k = new Kontak();
                k.setContactName(txtKontakNama.getText());
                k.setContactPhone(phone);

                Group g = (Group) cbGrup.getSelectedItem();
                
                if(g != null){
                    sms.getDB().insertKontakGroup(k, g);
                    refreshAll();
                }
                
                else{
                    JOptionPane.showMessageDialog(null, "Silakan pilih grup");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Format nomor salah");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kontak dan Nomor tidak boleh kosong");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddKontakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//            javax.swing.UIManager.setLookAndFeel("window");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SmsGUI gui = new SmsGUI();
            gui.setLocationRelativeTo(null);
            gui.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAddGrup;
    private javax.swing.JButton btnAddKontak;
    private javax.swing.JButton btnDeleteGrup;
    private javax.swing.JButton btnDeleteKontak;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnUpdateGrup;
    private javax.swing.JButton btnUpdateKontak;
    private javax.swing.JComboBox<String> cbGrup;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNomor;
    private javax.swing.JLabel lblNomor1;
    private javax.swing.JLabel lblNomor2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPanel pnlContacts;
    private javax.swing.JPanel pnlInbox;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSendSMS;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTable tblGrup;
    private javax.swing.JTable tblKontak;
    private javax.swing.JTextField txtGrupKode;
    private javax.swing.JTextField txtGrupNama;
    private javax.swing.JTextField txtKontakNama;
    private javax.swing.JTextField txtKontakNomor;
    private javax.swing.JTextField txtNomor;
    private javax.swing.JTextArea txtPesan;
    // End of variables declaration//GEN-END:variables

}
