package com.sms.entity;
// Generated Nov 14, 2017 11:22:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inbox generated by hbm2java
 */
public class Inbox  implements java.io.Serializable {


     private Integer inboxId;
     private String phoneNumber;
     private String message;
     private Date created;

    public Inbox() {
    }

    public Inbox(String phoneNumber, String message, Date created) {
       this.phoneNumber = phoneNumber;
       this.message = message;
       this.created = created;
    }
   
    public Integer getInboxId() {
        return this.inboxId;
    }
    
    public void setInboxId(Integer inboxId) {
        this.inboxId = inboxId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


