package com.sms.entity;
// Generated Nov 14, 2017 11:22:32 PM by Hibernate Tools 4.3.1

/**
 * Kontak generated by hbm2java
 */
public class Kontak implements java.io.Serializable {

    private Integer kontakId;
    private String contactName;
    private String contactPhone;

    public Kontak() {
    }

    public Kontak(String contactName, String contactPhone, String contactGroup) {
        this.contactName = contactName;
        this.contactPhone = contactPhone;

    }

    public Integer getKontakId() {
        return this.kontakId;
    }

    public void setKontakId(Integer kontakId) {
        this.kontakId = kontakId;
    }

    public String getContactName() {
        return this.contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactPhone() {
        return this.contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

}
