package com.sms.entity;
// Generated Nov 14, 2017 11:22:32 PM by Hibernate Tools 4.3.1

import java.util.Set;

/**
 * KontakGroup generated by hbm2java
 */
public class KontakGroup implements java.io.Serializable {

    private Integer groupId;
    private String groupName;
    private String groupCode;
    private Set<Kontak> kontaks;

    public KontakGroup() {
    }

    public KontakGroup(String groupName, String groupCode) {
        this.groupName = groupName;
        this.groupCode = groupCode;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getGroupCode() {
        return this.groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * @return the kontaks
     */
    public Set<Kontak> getKontaks() {
        return kontaks;
    }

    /**
     * @param kontaks the kontaks to set
     */
    public void setKontaks(Set<Kontak> kontaks) {
        this.kontaks = kontaks;
    }

}
